on:
  push:
    branches:
      - main
  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.milanorestaurant.com.pk
        username: test@milanorestaurant.com.pk
        password: CtWZBlH=5Iv)
        server-dir: /public_html/pos.milanorestaurant.com.pk/
